version: '3'

services:
  node:
    image: hrcarsan/node:14.17-chrome86
    user: node
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "Xvfb :99 -screen 0 1024x768x16 -ac -nolisten tcp -nolisten unix & node ./dist/examples/app/app.js"
    privileged: true
    ports:
      - 3214:3214
